'use client'

import Link from 'next/link'
import { useEffect, useRef, useState, type ReactNode } from 'react'
import { ArrowRight, ChevronDown, Menu, Moon, Sun, X } from 'lucide-react'
import { SteganographyField } from '@/components/motion/steganography-field'

const logoUrl = '/brand/oculiz-logo.png'
const questions = [
  ['What does OCULIZ verify?', 'Provenance, ownership records, metadata, watermarks, signatures, and forensic integrity signals.'],
  ['Can the signal survive image distribution?', 'The ownership layer is designed to remain recoverable across common export and distribution workflows.'],
  ['Does protection alter the original image?', 'No. The original stays preserved while protected derivatives and ownership records remain linked.'],
]

function MeteorField({ trigger = 0 }: { trigger?: number }) {
  const ref = useRef<HTMLCanvasElement>(null)
  useEffect(() => {
    const canvas = ref.current
    const ctx = canvas?.getContext('2d')
    if (!canvas || !ctx) return
    const reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches
    const points = Array.from({ length: 520 }, (_, i) => ({ x: Math.sin(i * 78.3) * .5 + .5, y: Math.sin(i * 39.7) * .5 + .5, phase: Math.sin(i * 12.4) * Math.PI, size: .35 + (i % 5) * .2 }))
    let w = 0, h = 0, raf = 0, time = 0, pulse = trigger ? 1 : 0, lastTrigger = trigger, launchedAt = trigger ? performance.now() : 0
    const resize = () => { const r = canvas.getBoundingClientRect(); const d = Math.min(devicePixelRatio || 1, 2); w = r.width; h = r.height; canvas.width = w * d; canvas.height = h * d; ctx.setTransform(d, 0, 0, d, 0, 0) }
    const run = () => {
      if (trigger !== lastTrigger) { lastTrigger = trigger; launchedAt = performance.now(); pulse = 1 }
      time += .004; pulse *= .985; ctx.clearRect(0, 0, w, h)
      points.forEach((p, i) => { const drift = reduced ? 0 : Math.sin(time + p.phase) * 4; const x = p.x * w + drift; const y = p.y * h + Math.cos(time * .7 + p.phase) * 3; const alpha = .06 + (i % 8) * .012 + pulse * .06; ctx.fillStyle = `rgba(126,182,255,${alpha})`; ctx.beginPath(); ctx.arc(x, y, p.size + pulse * .3, 0, Math.PI * 2); ctx.fill() })
      if (pulse > .02) { const t = Math.min(1, (performance.now() - launchedAt) / 2600); const x = w * (.12 + t * .74), y = h * (.04 + t * .82); const gradient = ctx.createLinearGradient(x - 240, y - 240, x, y); gradient.addColorStop(0, 'rgba(150,210,255,0)'); gradient.addColorStop(.76, 'rgba(91,165,255,.3)'); gradient.addColorStop(1, 'rgba(255,255,255,1)'); ctx.strokeStyle = gradient; ctx.lineWidth = 2 + (1 - t) * 5; ctx.shadowBlur = 28; ctx.shadowColor = '#6eaeff'; ctx.beginPath(); ctx.moveTo(x - 220, y - 220); ctx.lineTo(x, y); ctx.stroke(); ctx.shadowBlur = 0; if (t >= 1) pulse = 0 }
      raf = requestAnimationFrame(run)
    }
    resize(); addEventListener('resize', resize); raf = requestAnimationFrame(run)
    return () => { cancelAnimationFrame(raf); removeEventListener('resize', resize) }
  }, [trigger])
  return <canvas ref={ref} aria-hidden className="pointer-events-none absolute inset-0 h-full w-full" />
}

function Logo({ onClick }: { onClick?: () => void }) { return <button type="button" onClick={onClick} aria-label="Trigger OCULIZ meteor" className="rounded-md bg-white px-2 py-1 shadow-sm transition duration-500 hover:scale-[1.03]"><img src={logoUrl} alt="OCULIZ" className="h-11 w-auto" /></button> }
function ThemeToggle() { const [dark, setDark] = useState(false); useEffect(() => setDark(document.documentElement.classList.contains('dark')), []); const toggle = () => { const next = !dark; document.documentElement.classList.add('theme-transitioning'); document.documentElement.classList.toggle('dark', next); document.documentElement.style.colorScheme = next ? 'dark' : 'light'; localStorage.setItem('oculiz-theme', next ? 'dark' : 'light'); setDark(next); window.setTimeout(() => document.documentElement.classList.remove('theme-transitioning'), 850) }; return <button type="button" aria-label="Toggle color theme" onClick={toggle} className="theme-toggle grid h-10 w-10 place-items-center rounded-full border border-slate-300 text-slate-600 transition duration-700 hover:border-blue-500 hover:text-blue-600 dark:border-slate-700 dark:text-slate-300">{dark ? <Sun size={16} /> : <Moon size={16} />}</button> }

function Scene({ id, index, eyebrow, title, body, formation, children }: { id: string; index: string; eyebrow: string; title: string; body: string; formation: 'bits' | 'orbit' | 'matrix'; children: ReactNode }) {
  return <section id={id} className="scene-stage relative min-h-[220vh] overflow-hidden"><div className="sticky top-20 min-h-[calc(100vh-80px)]"><div className="scene-stage absolute inset-0"><SteganographyField formation={formation} density={440} className="opacity-95" />{children}</div><div className="relative z-10 mx-auto flex min-h-[calc(100vh-80px)] max-w-7xl items-end px-6 pb-20 pt-24 lg:px-10"><div className="flex w-full items-end justify-between gap-12"><div className="max-w-xl"><div className="font-mono text-[10px] uppercase tracking-[.24em] text-blue-300">{eyebrow}</div><h2 className="mt-5 text-5xl font-semibold leading-[.94] tracking-[-.08em] text-white sm:text-8xl">{title}</h2><p className="mt-7 max-w-md text-base leading-8 text-blue-100/70">{body}</p></div><div className="hidden pb-2 font-mono text-[10px] tracking-[.24em] text-blue-200/50 lg:block">SCENE {index} / 05</div></div></div></div></section>
}

function ToolEntry() {
  const [active, setActive] = useState<'generate' | 'register' | 'verify'>('verify')
  const tools = [
    { id: 'generate' as const, label: 'Generate', route: '/generate', eyebrow: 'Create + protect', copy: 'Make a new image and give it an identity from the first pixel.' },
    { id: 'register' as const, label: 'Register', route: '/register-image', eyebrow: 'Bring your image', copy: 'Attach provenance to an image created somewhere else.' },
    { id: 'verify' as const, label: 'Verify', route: '/verify', eyebrow: 'Read the signal', copy: 'Inspect ownership, signature, watermark, and integrity.' },
  ]
  return <section className="tool-entry relative overflow-hidden px-6 py-32 lg:px-10"><div className="absolute inset-0"><SteganographyField formation={active === 'verify' ? 'matrix' : active === 'register' ? 'orbit' : 'bits'} density={300} className="opacity-70" /></div><div className="relative z-10 mx-auto max-w-7xl"><div className="max-w-2xl"><div className="font-mono text-[10px] uppercase tracking-[.24em] text-blue-600 dark:text-blue-400">The signal is ready</div><h2 className="mt-5 text-5xl font-semibold tracking-[-.07em] text-slate-950 dark:text-white sm:text-8xl">Now use OCULIZ.</h2><p className="mt-6 max-w-lg text-lg leading-8 text-slate-600 dark:text-slate-300">Choose the next state for your image. Three paths, one continuous chain of trust.</p></div><div className="mt-20 grid gap-0 border-y border-slate-300/80 dark:border-slate-700/80 md:grid-cols-3">{tools.map((tool, index) => <Link key={tool.id} href={tool.route} onMouseEnter={() => setActive(tool.id)} onFocus={() => setActive(tool.id)} className={`tool-destination group relative min-h-64 border-slate-300/80 px-0 py-8 transition duration-700 dark:border-slate-700/80 md:px-8 ${index > 0 ? 'md:border-l' : ''} ${active === tool.id ? 'is-active' : ''}`}><div className="flex items-start justify-between"><span className="font-mono text-[10px] text-blue-600 dark:text-blue-400">0{index + 1}</span><ArrowRight size={18} className="text-slate-400 transition duration-500 group-hover:translate-x-2 group-hover:text-blue-600" /></div><div className="mt-16 font-mono text-[10px] uppercase tracking-[.18em] text-slate-500 dark:text-slate-400">{tool.eyebrow}</div><h3 className="mt-3 text-3xl font-semibold tracking-[-.05em] text-slate-950 dark:text-white">{tool.label}</h3><p className="mt-3 max-w-xs text-sm leading-6 text-slate-600 dark:text-slate-300">{tool.copy}</p><span className="tool-destination-line" /></Link>)}</div></div></section>
}

export default function HomeExperience() {
  const [menu, setMenu] = useState(false); const [meteor, setMeteor] = useState(0); const [faq, setFaq] = useState(0)
  return <main className="min-h-screen overflow-hidden bg-background text-foreground">
    <header className="sticky top-0 z-40 border-b border-slate-200/80 bg-[#f7f9fc]/85 backdrop-blur-xl dark:border-slate-800 dark:bg-[#0e1726]/85"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6 lg:px-10"><Logo onClick={() => setMeteor(Date.now())} /><nav className="hidden items-center gap-9 text-sm text-slate-600 md:flex dark:text-slate-300"><a href="#identity">Identity</a><a href="#proof">Proof</a><a href="#watermark">Watermark</a><a href="#faq">FAQ</a></nav><div className="hidden items-center gap-3 md:flex"><ThemeToggle /><Link href="/login" className="btn-base btn-outline">Sign in</Link><Link href="/register" className="btn-base btn-primary">Get started <ArrowRight size={15} /></Link></div><button type="button" aria-label="Open navigation" onClick={() => setMenu(!menu)} className="rounded-full p-2 md:hidden">{menu ? <X /> : <Menu />}</button></div>{menu && <div className="border-t border-slate-200 px-6 py-5 dark:border-slate-800 md:hidden"><div className="flex flex-col gap-5 text-sm"><a href="#identity" onClick={() => setMenu(false)}>Identity</a><a href="#proof" onClick={() => setMenu(false)}>Proof</a><a href="#watermark" onClick={() => setMenu(false)}>Watermark</a><Link href="/register" className="btn-base btn-primary w-fit">Get started <ArrowRight size={15} /></Link></div></div>}</header>
    <section className="relative min-h-[calc(100vh-80px)] overflow-hidden"><MeteorField trigger={meteor} /><div className="relative mx-auto flex min-h-[calc(100vh-80px)] max-w-7xl items-center px-6 py-24 lg:px-10"><div className="max-w-5xl"><div className="mb-8 flex items-center gap-3 font-mono text-[10px] uppercase tracking-[.24em] text-blue-600 dark:text-blue-400"><span className="h-px w-10 bg-blue-500" />Ownership infrastructure / 01</div><h1 className="max-w-5xl text-[clamp(4rem,10vw,10rem)] font-semibold leading-[.88] tracking-[-.09em] text-slate-950 dark:text-white">Trust,<br /><span className="text-blue-600 dark:text-blue-400">built into</span><br />every pixel.</h1><p className="mt-10 max-w-xl text-lg leading-8 text-slate-600 dark:text-slate-300">AI can create. OCULIZ gives creation an identity, a provenance trail, and proof that travels with the image.</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/generate" className="btn-base btn-primary">Start with an image <ArrowRight size={15} /></Link><Link href="/verify" className="btn-base btn-outline">Open verifier</Link></div></div></div><div className="absolute bottom-8 left-1/2 -translate-x-1/2 font-mono text-[10px] uppercase tracking-[.24em] text-slate-400">Scroll to reveal the signal</div></section>
    <Scene id="identity" index="02" eyebrow="Creation / identity" title="AI can create." body="Creation is only the first state. Watch a dispersed image field converge slowly around a single, recoverable identity." formation="bits"><div className="absolute inset-0 grid place-items-center"><div className="h-64 w-64 rounded-full border border-blue-300/25 shadow-[0_0_120px_rgba(61,137,255,.24)]" /><div className="absolute font-mono text-[10px] tracking-[.2em] text-blue-100">IMAGE ID / OC-24A91F</div></div></Scene>
    <Scene id="proof" index="03" eyebrow="Forensics / proof" title="Creation needs proof." body="The field stops behaving like noise. Hash, timestamp, signature, and integrity resolve into a clean chain of custody." formation="orbit"><div className="absolute left-6 top-24 font-mono text-[10px] leading-8 text-blue-100/70 sm:left-12"><div>HASH / A91F-22C0-88</div><div>SIGNATURE / MATCHED</div><div>INTEGRITY / BACKEND CHECK</div></div><div className="absolute left-0 right-0 top-1/2 h-px bg-blue-300/50 shadow-[0_0_28px_4px_rgba(96,165,250,.35)]" /></Scene>
    <Scene id="watermark" index="04" eyebrow="Steganography / provenance" title="Proof needs provenance." body="An invisible watermark emerges below the visible surface. It is not decoration; it is the ownership signal embedded into the image." formation="matrix"><div className="absolute inset-0 bg-[radial-gradient(circle_at_center,transparent_0_18%,rgba(4,12,27,.18)_45%,rgba(4,12,27,.86)_100%)]" /><div className="absolute bottom-10 left-6 flex gap-8 font-mono text-[10px] text-blue-200 sm:left-12"><span>WATERMARK / ACTIVE</span><span>PIXEL DELTA / 0.00%</span></div></Scene>
    <section className="relative min-h-[180vh]"><div className="sticky top-20 flex min-h-[calc(100vh-80px)] items-center"><div className="mx-auto max-w-7xl px-6 py-24 text-center lg:px-10"><div className="font-mono text-[10px] uppercase tracking-[.24em] text-blue-600 dark:text-blue-400">Signal / trust / 05</div><h2 className="mx-auto mt-6 text-6xl font-semibold tracking-[-.08em] text-slate-950 dark:text-white sm:text-9xl">OCULIZ.</h2><p className="mx-auto mt-8 max-w-xl text-lg leading-8 text-slate-600 dark:text-slate-300">One signal. Every surface. The identity settles into a verification-ready record.</p><div className="mx-auto mt-12 h-px max-w-md bg-blue-600" /></div></div></section>
    <ToolEntry />
    <section id="faq" className="mx-auto max-w-4xl px-6 py-32"><div className="text-center"><div className="font-mono text-[10px] uppercase tracking-[.24em] text-blue-600 dark:text-blue-400">Clear answers / 06</div><h2 className="mt-5 text-5xl font-semibold tracking-[-.07em] text-slate-950 dark:text-white">Built for scrutiny.</h2></div><div className="mt-12 divide-y divide-slate-200 border-y border-slate-200 dark:divide-slate-800 dark:border-slate-800">{questions.map(([q, a], i) => <div key={q} className="py-6"><button type="button" onClick={() => setFaq(faq === i ? -1 : i)} className="flex w-full items-center justify-between text-left font-medium text-slate-900 dark:text-white">{q}<ChevronDown size={18} className={`transition ${faq === i ? 'rotate-180 text-blue-600' : 'text-slate-400'}`} /></button>{faq === i && <p className="mt-4 max-w-2xl text-sm leading-7 text-slate-600 dark:text-slate-300">{a}</p>}</div>)}</div></section>
    <footer className="border-t border-slate-200 dark:border-slate-800"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-6 py-12 sm:flex-row sm:items-end sm:justify-between lg:px-10"><div><Logo /><p className="mt-4 max-w-xs text-sm text-slate-500">Protect. Verify. Own. The provenance layer for AI-generated imagery.</p></div><Link href="/verify" className="btn-base btn-primary">Verify an image <ArrowRight size={15} /></Link></div></footer>
  </main>
}
