'use client'

import { useEffect, useState } from 'react'
import type { ReactNode } from 'react'
import Link from 'next/link'
import { ArrowRight, ChevronDown, Fingerprint, Menu, ScanLine, ShieldCheck, X } from 'lucide-react'
import { LogoInteraction } from '@/components/brand/logo-interaction'
import { MorphingParticleField } from '@/components/motion/morphing-particle-field'

const stages = ['Reading image', 'Inspecting provenance', 'Searching watermark', 'Validating signature', 'Comparing fingerprint', 'Analyzing integrity']
const useCases = ['Digital artists', 'Media organizations', 'Legal evidence', 'Insurance', 'Enterprise AI', 'Social platforms']

function ThemeToggle() {
  const [dark, setDark] = useState(false)
  useEffect(() => setDark(document.documentElement.classList.contains('dark')), [])
  const toggle = () => { const next = !dark; document.documentElement.classList.toggle('dark', next); document.documentElement.style.colorScheme = next ? 'dark' : 'light'; localStorage.setItem('oculiz-theme', next ? 'dark' : 'light'); setDark(next) }
  return <button type="button" onClick={toggle} aria-label="Toggle color theme" className="flex h-9 w-9 items-center justify-center rounded-md border border-slate-300 text-slate-600 transition hover:border-blue-500 hover:text-blue-600 dark:border-slate-700 dark:text-slate-300">{dark ? '☼' : '◐'}</button>
}

function ForensicVisual() {
  const [active, setActive] = useState(3)
  return <div className="scene-visual relative overflow-hidden rounded-2xl p-4 text-slate-100 sm:p-6"><div className="relative z-10 flex items-center justify-between border-b border-white/10 pb-4"><span className="mono-label text-blue-200">forensic viewer / live</span><span className="font-mono text-[10px] text-emerald-300">READY / 99.8%</span></div><div className="relative z-10 mt-5 grid gap-5 sm:grid-cols-[1.12fr_.88fr]"><div className="relative aspect-[4/5] overflow-hidden rounded-xl bg-[#0c1c31]"><div className="absolute inset-0 opacity-70" style={{ backgroundImage: 'radial-gradient(circle at 44% 32%, rgba(134,180,255,.42), transparent 18%), linear-gradient(145deg, rgba(35,65,104,.4), rgba(5,12,24,.95)), repeating-linear-gradient(0deg, transparent 0 8px, rgba(147,197,253,.08) 9px)' }} /><div className="absolute inset-x-0 h-px bg-blue-200 shadow-[0_0_20px_6px_rgba(96,165,250,.85)] transition-transform duration-700" style={{ transform: `translateY(${18 + active * 13}vh)` }} /><div className="absolute bottom-4 left-4 font-mono text-[10px] text-blue-200">PIXEL SCAN / 0{active + 1}</div></div><div className="space-y-2">{stages.map((stage, index) => <button key={stage} type="button" onClick={() => setActive(index)} className={`flex w-full items-center gap-3 rounded-lg border p-3 text-left text-xs transition ${active === index ? 'border-blue-400/60 bg-blue-500/15 text-white' : 'border-white/10 bg-white/5 text-slate-300 hover:bg-white/10'}`}><span className={`h-2 w-2 rounded-full ${index < active ? 'bg-emerald-400' : index === active ? 'animate-pulse bg-blue-400' : 'bg-slate-600'}`} />{stage}<span className="ml-auto font-mono text-[10px] text-slate-500">{index < active ? 'done' : index === active ? 'live' : 'queued'}</span></button>)}</div></div><div className="relative z-10 mt-5 grid grid-cols-3 gap-2 font-mono text-[10px] text-slate-400"><span>HASH / A91F</span><span>WATERMARK / FOUND</span><span className="text-right text-emerald-300">AUTHENTIC</span></div></div>
}

function Scene({ id, eyebrow, title, body, children, reverse = false }: { id?: string; eyebrow: string; title: string; body: string; children: ReactNode; reverse?: boolean }) {
  return <section id={id} className="cinematic-track border-b border-slate-200 dark:border-slate-800"><div className={`cinematic-pin mx-auto grid max-w-7xl gap-12 px-6 py-20 lg:grid-cols-2 lg:gap-24 lg:px-10 ${reverse ? 'lg:[&>div:first-child]:order-2' : ''}`}><div className="self-center"><div className="mono-label text-blue-600 dark:text-blue-400">{eyebrow}</div><h2 className="mt-5 max-w-xl text-4xl font-semibold tracking-[-0.055em] text-slate-950 dark:text-white sm:text-6xl">{title}</h2><p className="mt-6 max-w-md text-base leading-8 text-slate-600 dark:text-slate-300">{body}</p></div><div className="relative">{children}</div></div></section>
}

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [faq, setFaq] = useState(0)
  return <main className="min-h-screen overflow-hidden bg-background"><header className="sticky top-0 z-40 border-b border-slate-200/80 bg-[#f7f9fc]/90 backdrop-blur dark:border-slate-800 dark:bg-[#0e1726]/90"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6 lg:px-10"><LogoInteraction /><nav className="hidden items-center gap-8 text-sm text-slate-600 md:flex dark:text-slate-300"><a href="#identity" className="hover:text-blue-600">Identity</a><a href="#verification" className="hover:text-blue-600">Verification</a><a href="#network" className="hover:text-blue-600">Network</a><a href="#faq" className="hover:text-blue-600">FAQ</a></nav><div className="hidden items-center gap-3 md:flex"><ThemeToggle /><Link href="/login" className="btn-base btn-outline">Sign in</Link><Link href="/register" className="btn-base btn-primary">Get started <ArrowRight size={15} /></Link></div><button type="button" aria-label="Open navigation" onClick={() => setMenuOpen(!menuOpen)} className="rounded-md p-2 md:hidden">{menuOpen ? <X /> : <Menu />}</button></div>{menuOpen && <div className="border-t border-slate-200 px-6 py-5 dark:border-slate-800 md:hidden"><div className="flex flex-col gap-4 text-sm"><a href="#identity" onClick={() => setMenuOpen(false)}>Identity</a><a href="#verification" onClick={() => setMenuOpen(false)}>Verification</a><a href="#network" onClick={() => setMenuOpen(false)}>Network</a><Link href="/register" className="btn-base btn-primary w-fit">Get started <ArrowRight size={15} /></Link></div></div>}</header>

<section className="relative flex min-h-[calc(100vh-80px)] items-center border-b border-slate-200 dark:border-slate-800"><div className="absolute inset-0"><MorphingParticleField density={170} className="opacity-75" /></div><div className="relative mx-auto grid w-full max-w-7xl items-center gap-16 px-6 py-24 lg:grid-cols-[1.04fr_.96fr] lg:px-10"><div><div className="mono-label mb-6 flex items-center gap-3 text-blue-600 dark:text-blue-400"><span className="h-px w-8 bg-blue-500" />OWNERSHIP INFRASTRUCTURE / 01</div><h1 className="max-w-4xl text-6xl font-semibold tracking-[-0.07em] text-slate-950 dark:text-white sm:text-8xl">Trust, built into every pixel.</h1><p className="mt-8 max-w-xl text-lg leading-8 text-slate-600 dark:text-slate-300">OCULIZ makes AI-generated imagery defensible. Register provenance, protect ownership, and verify the signal wherever the image travels.</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/generate" className="btn-base btn-primary">Start with an image <ArrowRight size={15} /></Link><Link href="/verify" className="btn-base btn-outline">Open verifier</Link></div><div className="mt-14 flex flex-wrap gap-6 font-mono text-[10px] uppercase tracking-[.14em] text-slate-500"><span>SHA-256</span><span>Invisible watermark</span><span>Audit-ready</span></div></div><div className="relative mx-auto w-full max-w-lg"><div className="scene-visual relative aspect-[4/5] rounded-2xl p-6"><MorphingParticleField density={95} className="opacity-70" /><div className="absolute inset-8 rounded-xl border border-blue-300/20 bg-[linear-gradient(145deg,rgba(83,127,190,.25),rgba(5,12,24,.95)),repeating-linear-gradient(90deg,transparent_0_12px,rgba(255,255,255,.04)_13px)]" /><div className="absolute bottom-10 left-10 right-10 rounded-lg border border-blue-300/30 bg-[#0b192b]/85 p-4 font-mono text-[10px] text-blue-100"><div className="flex justify-between"><span>IMAGE ID</span><span>OC-24A91F</span></div><div className="mt-3 h-1 bg-blue-500/20"><div className="h-full w-[78%] bg-blue-400 data-pulse" /></div><div className="mt-3 flex justify-between text-slate-400"><span>IDENTITY LOCKED</span><span>78%</span></div></div></div></div></div></section>

<Scene eyebrow="SCROLL-LINKED IDENTITY / 02" title="An image becomes a record." body="The source stays visible while its hidden structure emerges: identity, timestamp, fingerprint, and the ownership signal that gives it context."><div id="identity" className="scene-visual relative min-h-[560px] overflow-hidden rounded-2xl"><MorphingParticleField density={240} className="opacity-95" /><div className="absolute inset-0 bg-[radial-gradient(circle_at_center,transparent_0_18%,rgba(2,6,23,.2)_62%,rgba(2,6,23,.88))]" /><div className="absolute left-7 top-8 space-y-3 font-mono text-[10px] text-blue-200"><div className="signal-line">IMAGE ID / OC-24A91F</div><div className="signal-line">HASH / A91F-22C0-88</div><div className="signal-line">FINGERPRINT / MATCHED</div></div><div className="absolute bottom-7 left-7 font-mono text-[10px] tracking-[.14em] text-blue-200">SCROLL PROGRESS CONTROLS STATE</div></div></Scene>

<Scene id="verification" eyebrow="FORENSIC VERIFICATION / 03" title="The process is the proof." body="A final verdict is only as credible as the evidence behind it. OCULIZ keeps every inspection stage visible, reviewable, and ready to connect to real forensic jobs." reverse><ForensicVisual /></Scene>

<Scene eyebrow="INVISIBLE WATERMARK / 04" title="Protection without visual compromise." body="The visible image remains stable while the ownership signal lives inside it. Pixel layers, scan lines, and metadata move as one continuous system."><div className="scene-visual relative min-h-[480px] overflow-hidden rounded-2xl p-8"><div className="absolute inset-0 opacity-75" style={{ backgroundImage: 'repeating-linear-gradient(0deg, transparent 0 8px, rgba(96,165,250,.13) 9px), repeating-linear-gradient(90deg, transparent 0 12px, rgba(96,165,250,.08) 13px)' }} /><div className="relative flex min-h-[400px] flex-col justify-between"><div className="flex justify-between font-mono text-[10px] text-blue-200"><span>WATERMARK LAYER</span><span>INVISIBLE / ACTIVE</span></div><div className="mx-auto h-48 w-72 rounded-xl bg-[linear-gradient(130deg,#334155,#0f172a)] shadow-[0_0_90px_rgba(37,99,235,.25)]"><div className="h-full rounded-xl opacity-25" style={{ backgroundImage: 'radial-gradient(#93c5fd 1px, transparent 1px)', backgroundSize: '9px 9px' }} /></div><div className="grid grid-cols-3 gap-3 font-mono text-[10px] text-slate-400"><span>PIXEL DELTA / 0.00%</span><span>KEY / A91F</span><span className="text-right text-emerald-300">PRESERVED</span></div></div></div></Scene>

<section id="network" className="border-y border-slate-200 bg-white dark:border-slate-800 dark:bg-[#101c2d]"><div className="mx-auto max-w-7xl px-6 py-28 lg:px-10"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><div className="mono-label text-blue-600 dark:text-blue-400">NETWORK / 05</div><h2 className="mt-5 text-5xl font-semibold tracking-[-0.055em] text-slate-950 dark:text-white">One signal. Every surface.</h2></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{useCases.map((item, index) => <div key={item} className="group flex min-h-40 flex-col justify-between border border-slate-200 p-5 transition hover:-translate-y-1 hover:border-blue-400 dark:border-slate-800"><span className="font-mono text-[10px] text-blue-600">0{index + 1}</span><span className="text-lg font-medium text-slate-800 dark:text-slate-100">{item}</span><ArrowRight size={16} className="text-slate-400 transition group-hover:translate-x-1 group-hover:text-blue-500" /></div>)}</div></div></div></section>

<section id="faq" className="mx-auto max-w-4xl px-6 py-28"><div className="text-center"><div className="mono-label text-blue-600 dark:text-blue-400">CLEAR ANSWERS / 06</div><h2 className="mt-5 text-5xl font-semibold tracking-[-0.055em] text-slate-950 dark:text-white">Built for scrutiny.</h2></div><div className="mt-12 divide-y divide-slate-200 border-y border-slate-200 dark:divide-slate-800 dark:border-slate-800">{[['What does OCULIZ verify?', 'Provenance, ownership records, metadata, watermarks, signatures, and forensic integrity signals.'], ['Can teams connect their own backend?', 'Yes. The staged verification state model is designed to map cleanly to API responses and real forensic jobs.'], ['Does protection alter the original image?', 'No. The original remains preserved while protected derivatives and ownership records are tracked separately.']].map(([question, answer], index) => <div key={question} className="py-6"><button type="button" onClick={() => setFaq(faq === index ? -1 : index)} className="flex w-full items-center justify-between text-left font-medium text-slate-900 dark:text-white">{question}<ChevronDown size={18} className={`transition ${faq === index ? 'rotate-180 text-blue-600' : 'text-slate-400'}`} /></button>{faq === index && <p className="mt-4 max-w-2xl pr-8 text-sm leading-7 text-slate-600 dark:text-slate-300">{answer}</p>}</div>)}</div></section>

<footer className="border-t border-slate-200 dark:border-slate-800"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-6 py-12 sm:flex-row sm:items-end sm:justify-between lg:px-10"><div><LogoInteraction compact /><p className="mt-4 max-w-xs text-sm text-slate-500">Protect. Verify. Own. The provenance layer for AI-generated imagery.</p></div><div className="flex flex-wrap gap-3"><Link href="/generate" className="btn-base btn-outline">Generate</Link><Link href="/register-image" className="btn-base btn-outline">Register</Link><Link href="/verify" className="btn-base btn-primary">Verify <ArrowRight size={15} /></Link></div></div></footer></main> }
