'use client'

import { useState } from 'react'
import Link from 'next/link'
import { ArrowRight, Check, ChevronDown, Fingerprint, Menu, ScanLine, ShieldCheck, X } from 'lucide-react'
import { LogoInteraction } from '@/components/brand/logo-interaction'
import { MorphingParticleField } from '@/components/motion/morphing-particle-field'

const signals = ['Reading image', 'Inspecting provenance', 'Searching for watermark', 'Validating signature', 'Comparing fingerprint', 'Analyzing integrity', 'Generating verdict']
const useCases = ['Digital artists', 'Media organizations', 'Legal evidence', 'Insurance', 'Enterprise AI', 'Social platforms']

function ThemeToggle() {
  const [dark, setDark] = useState(() => typeof document !== 'undefined' && document.documentElement.classList.contains('dark'))
  const toggle = () => {
    const next = !dark
    document.documentElement.classList.toggle('dark', next)
    document.documentElement.style.colorScheme = next ? 'dark' : 'light'
    localStorage.setItem('oculiz-theme', next ? 'dark' : 'light')
    setDark(next)
  }
  return <button type="button" onClick={toggle} aria-label="Toggle color theme" className="flex h-9 w-9 items-center justify-center rounded-md border border-slate-300 text-slate-600 transition hover:border-blue-500 hover:text-blue-600 dark:border-slate-700 dark:text-slate-300">{dark ? '☼' : '◐'}</button>
}

function VerificationSequence() {
  const [active, setActive] = useState(4)
  return <div className="panel overflow-hidden bg-slate-950 p-4 text-slate-100 shadow-2xl shadow-blue-950/20 sm:p-6">
    <div className="flex items-center justify-between border-b border-white/10 pb-4"><span className="mono-label text-blue-300">forensic viewer / live</span><span className="font-mono text-[10px] text-emerald-300">READY / 99.8%</span></div>
    <div className="mt-5 grid gap-4 sm:grid-cols-[1fr_.9fr]">
      <div className="relative aspect-square overflow-hidden rounded-lg bg-slate-800"><div className="absolute inset-0 bg-[radial-gradient(circle_at_38%_30%,rgba(255,255,255,.3),transparent_17%),linear-gradient(135deg,rgba(30,41,59,.2),rgba(37,99,235,.45)),repeating-linear-gradient(0deg,rgba(255,255,255,.06)_0_1px,transparent_1px_8px)]" /><div className="absolute inset-x-0 top-0 h-px bg-blue-300 shadow-[0_0_18px_4px_rgba(96,165,250,.75)] transition-transform duration-700" style={{ transform: `translateY(${16 + active * 15}%)` }} /><div className="absolute bottom-3 left-3 font-mono text-[10px] text-blue-200">PIXEL SCAN / 04</div></div>
      <div className="space-y-2">{signals.map((item, index) => <button type="button" key={item} onClick={() => setActive(index)} className={`flex w-full items-center gap-3 rounded border p-3 text-left text-xs transition ${active === index ? 'border-blue-400/60 bg-blue-500/15 text-white' : 'border-white/10 bg-white/5 text-slate-300 hover:bg-white/10'}`}><span className={`h-2 w-2 rounded-full ${index < active ? 'bg-emerald-400' : index === active ? 'animate-pulse bg-blue-400' : 'bg-slate-600'}`} />{item}<span className="ml-auto font-mono text-[10px] text-slate-500">{index < active ? 'done' : index === active ? 'live' : 'queued'}</span></button>)}</div>
    </div>
  </div>
}

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [openFaq, setOpenFaq] = useState(0)
  return <main className="min-h-screen overflow-hidden bg-background">
    <header className="sticky top-0 z-40 border-b border-slate-200/80 bg-background/90 backdrop-blur dark:border-slate-800"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6 lg:px-10"><LogoInteraction /><nav className="hidden items-center gap-8 text-sm text-slate-600 md:flex dark:text-slate-300"><a href="#platform" className="transition hover:text-blue-600">Platform</a><a href="#identity" className="transition hover:text-blue-600">Identity</a><a href="#verification" className="transition hover:text-blue-600">Verification</a><a href="#faq" className="transition hover:text-blue-600">FAQ</a></nav><div className="hidden items-center gap-3 md:flex"><ThemeToggle /><Link href="/login" className="btn-base btn-outline">Sign in</Link><Link href="/register" className="btn-base btn-primary">Get started <ArrowRight size={15} /></Link></div><button type="button" aria-label="Open navigation" onClick={() => setMenuOpen(!menuOpen)} className="rounded-md p-2 md:hidden">{menuOpen ? <X /> : <Menu />}</button></div>{menuOpen && <div className="border-t border-slate-200 px-6 py-5 dark:border-slate-800 md:hidden"><div className="flex flex-col gap-4 text-sm"><a href="#platform" onClick={() => setMenuOpen(false)}>Platform</a><a href="#identity" onClick={() => setMenuOpen(false)}>Identity</a><a href="#verification" onClick={() => setMenuOpen(false)}>Verification</a><Link href="/register" className="btn-base btn-primary w-fit">Get started <ArrowRight size={15} /></Link></div></div>}</header>

    <section id="platform" className="shell-grid relative border-b border-slate-200/80 dark:border-slate-800"><div className="absolute inset-0"><MorphingParticleField density={150} className="opacity-70" /></div><div className="relative mx-auto grid max-w-7xl items-center gap-16 px-6 py-24 lg:grid-cols-[1.02fr_.98fr] lg:px-10 lg:py-36"><div><div className="mono-label mb-6 flex items-center gap-3 text-blue-600 dark:text-blue-400"><span className="h-px w-8 bg-blue-500" />OWNERSHIP INFRASTRUCTURE / 01</div><h1 className="max-w-3xl text-5xl font-semibold tracking-[-0.065em] text-slate-950 sm:text-7xl dark:text-white">Digital ownership for the age of AI.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-600 dark:text-slate-300">OCULIZ turns generated images into defensible records. Protect the source, verify the signal, and make ownership legible wherever the image travels.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/generate" className="btn-base btn-primary">Generate <ArrowRight size={15} /></Link><Link href="/register-image" className="btn-base btn-outline">Register</Link><Link href="/verify" className="btn-base btn-outline">Verify</Link></div><div className="mt-12 flex flex-wrap gap-6 font-mono text-[10px] uppercase tracking-[.13em] text-slate-500"><span>SHA-256</span><span>Invisible watermark</span><span>Audit-ready</span></div></div><div className="relative mx-auto w-full max-w-xl"><div className="relative aspect-[4/5] overflow-hidden rounded-xl border border-slate-300 bg-slate-950 p-5 shadow-2xl dark:border-slate-700"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_30%,rgba(72,116,204,.22),transparent_42%)]" /><div className="absolute inset-7 rounded-lg border border-blue-300/20 bg-[linear-gradient(135deg,rgba(100,116,139,.28),rgba(15,23,42,.95)),repeating-linear-gradient(90deg,transparent_0_11px,rgba(255,255,255,.025)_12px)]" /><div className="absolute bottom-9 left-9 right-9 rounded border border-blue-300/30 bg-slate-950/80 p-4 font-mono text-[10px] text-blue-200 backdrop-blur"><div className="flex justify-between"><span>IMAGE ID</span><span>OC-2048-A91F</span></div><div className="mt-2 flex justify-between text-emerald-300"><span>OWNERSHIP</span><span>VERIFIED</span></div></div><div className="absolute left-10 top-10 rounded border border-white/10 bg-white/5 px-3 py-2 font-mono text-[10px] text-slate-300">SOURCE / ORIGINAL</div></div><div className="absolute -bottom-5 -left-5 rounded border border-slate-300 bg-background px-4 py-3 font-mono text-[10px] text-slate-600 shadow-lg dark:border-slate-700 dark:text-slate-300"><span className="mr-2 inline-block h-2 w-2 rounded-full bg-emerald-400" />SIGNATURE VALID</div></div></div></section>

    <section id="identity" className="scene-track border-b border-slate-200 dark:border-slate-800"><div className="scene-pin mx-auto grid max-w-7xl gap-12 px-6 py-24 lg:grid-cols-[.72fr_1.28fr] lg:px-10"><div className="max-w-md"><div className="mono-label text-blue-600 dark:text-blue-400">SCROLL-LINKED IDENTITY / 02</div><h2 className="mt-5 text-4xl font-semibold tracking-[-0.05em] text-slate-950 dark:text-white">Watch a file become a signal.</h2><p className="mt-5 leading-7 text-slate-600 dark:text-slate-300">Scroll through the field. Dispersed pixels converge into an identity structure, then dissolve into the evidence needed to defend it.</p><div className="mt-9 space-y-3">{['Dispersed source', 'Organized fingerprint', 'Ownership structure', 'Watermark signal', 'Dissolve into proof'].map((item, index) => <div key={item} className="flex items-center gap-4 border-b border-slate-200 py-3 text-sm dark:border-slate-800"><span className="font-mono text-[10px] text-blue-600">0{index + 1}</span><span>{item}</span><span className="ml-auto h-1.5 w-1.5 rounded-full bg-blue-500" /></div>)}</div></div><div className="relative min-h-[560px] overflow-hidden rounded-xl bg-slate-950"><MorphingParticleField density={230} className="opacity-90" /><div className="absolute inset-0 bg-[radial-gradient(circle_at_center,transparent_0_20%,rgba(2,6,23,.2)_66%,rgba(2,6,23,.8))]" /><div className="absolute bottom-6 left-6 font-mono text-[10px] tracking-[.14em] text-blue-200">MORPH ENGINE / SCROLL POSITION CONTROLS STATE</div></div></div></section>

    <section id="verification" className="border-b border-slate-200 bg-slate-50 dark:border-slate-800 dark:bg-[#101c2d]"><div className="mx-auto grid max-w-7xl gap-12 px-6 py-24 lg:grid-cols-[.85fr_1.15fr] lg:px-10"><div className="self-center"><div className="mono-label text-blue-600 dark:text-blue-400">FORENSIC WORKSPACE / 03</div><h2 className="mt-5 text-4xl font-semibold tracking-[-0.05em] text-slate-950 dark:text-white">The proof is in the process.</h2><p className="mt-5 max-w-md leading-7 text-slate-600 dark:text-slate-300">A verdict without a trail is only a label. OCULIZ keeps every inspection stage visible, reviewable, and ready to connect to your own backend later.</p><Link href="/verify" className="btn-base btn-primary mt-8">Open verification workspace <ArrowRight size={15} /></Link></div><VerificationSequence /></div></section>

    <section className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><div className="grid gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><div className="mono-label text-blue-600 dark:text-blue-400">HIDDEN LAYER / 04</div><h2 className="mt-5 text-4xl font-semibold tracking-[-0.05em] text-slate-950 dark:text-white">Protection without visual compromise.</h2><p className="mt-5 leading-7 text-slate-600 dark:text-slate-300">The visible image remains stable while the ownership signal lives inside it. Reveal the layer, not the source.</p></div><div className="panel relative min-h-[360px] overflow-hidden bg-slate-950 p-7 text-slate-100"><div className="absolute inset-0 opacity-70" style={{ backgroundImage: 'repeating-linear-gradient(0deg, transparent 0 8px, rgba(96,165,250,.14) 9px), repeating-linear-gradient(90deg, transparent 0 12px, rgba(96,165,250,.1) 13px)' }} /><div className="relative flex h-full min-h-[300px] flex-col justify-between"><div className="flex items-center justify-between font-mono text-[10px] text-blue-200"><span>WATERMARK LAYER</span><span>INVISIBLE / ACTIVE</span></div><div className="mx-auto h-40 w-64 rounded-lg bg-[linear-gradient(130deg,#334155,#0f172a)] shadow-[0_0_80px_rgba(37,99,235,.22)]"><div className="h-full w-full rounded-lg opacity-20" style={{ backgroundImage: 'radial-gradient(#93c5fd 1px, transparent 1px)', backgroundSize: '9px 9px' }} /></div><div className="grid grid-cols-3 gap-3 font-mono text-[10px] text-slate-400"><span>PIXEL DELTA / 0.00%</span><span>KEY / A91F</span><span className="text-right text-emerald-300">PRESERVED</span></div></div></div></div></section>

    <section className="border-y border-slate-200 bg-white dark:border-slate-800 dark:bg-[#101c2d]"><div className="mx-auto max-w-7xl px-6 py-20 lg:px-10"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><div className="mono-label text-blue-600 dark:text-blue-400">BUILT FOR THE RECORD / 05</div><h2 className="mt-5 text-4xl font-semibold tracking-[-0.05em] text-slate-950 dark:text-white">A trust layer for every image surface.</h2></div><p className="max-w-md leading-7 text-slate-600 dark:text-slate-300">From first render to final evidence, OCULIZ gives teams a common language for authenticity.</p></div><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{useCases.map((item, index) => <div key={item} className="group flex min-h-36 flex-col justify-between rounded-lg border border-slate-200 p-5 transition hover:-translate-y-1 hover:border-blue-400 dark:border-slate-800 dark:hover:border-blue-500"><span className="font-mono text-[10px] text-blue-600">0{index + 1}</span><span className="text-lg font-medium text-slate-800 dark:text-slate-100">{item}</span><ArrowRight size={16} className="text-slate-400 transition group-hover:translate-x-1 group-hover:text-blue-500" /></div>)}</div></div></section>

    <section id="faq" className="mx-auto max-w-4xl px-6 py-24"><div className="text-center"><div className="mono-label text-blue-600 dark:text-blue-400">CLEAR ANSWERS / 06</div><h2 className="mt-5 text-4xl font-semibold tracking-[-0.05em] text-slate-950 dark:text-white">Built for scrutiny.</h2></div><div className="mt-10 divide-y divide-slate-200 border-y border-slate-200 dark:divide-slate-800 dark:border-slate-800">{[['What does OCULIZ verify?', 'OCULIZ inspects provenance, ownership records, metadata, watermarks, signatures, and forensic integrity signals.'], ['Can teams connect their own verification backend?', 'Yes. The verification workspace exposes a staged state model that can map directly to API responses and real forensic jobs.'], ['Does protection alter the original image?', 'The original remains preserved. Protection workflows create a tracked derivative while keeping the source record intact.']].map(([question, answer], index) => <div key={question} className="py-5"><button type="button" onClick={() => setOpenFaq(openFaq === index ? -1 : index)} className="flex w-full items-center justify-between text-left font-medium text-slate-900 dark:text-white">{question}<ChevronDown size={18} className={`transition ${openFaq === index ? 'rotate-180 text-blue-600' : 'text-slate-400'}`} /></button>{openFaq === index && <p className="mt-4 max-w-2xl pr-8 text-sm leading-7 text-slate-600 dark:text-slate-300">{answer}</p>}</div>)}</div></section>

    <footer className="border-t border-slate-200 dark:border-slate-800"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-6 py-10 sm:flex-row sm:items-end sm:justify-between lg:px-10"><div><LogoInteraction compact /><p className="mt-4 max-w-xs text-sm text-slate-500">Protect. Verify. Own. The provenance layer for AI-generated imagery.</p></div><div className="flex flex-wrap gap-3"><Link href="/generate" className="btn-base btn-outline">Generate</Link><Link href="/register-image" className="btn-base btn-outline">Register</Link><Link href="/verify" className="btn-base btn-primary">Verify <ArrowRight size={15} /></Link></div></div></footer>
  </main>
}

export default function Home() { return <App /> }
